### ISSUE TITLE
Try to update to 0.11.3 

### ISSUE THREAD

**Issue by perdicaro** [TediCross/TediCross#242]
Hello, i have this error message when i update to 0.11.3:  

C:\Users\Administrator\Desktop\TediCross-0.11.3>npm install --production
npm WARN config production Use `--omit=dev` instead.

> tedicross@0.11.2 postinstall
> npm run build

> tedicross@0.11.2 build
> tsc

src/main.ts:96:111 - error TS2339: Property 'MESSAGE_CONTENT' does not exist on type 'Record<IntentsString, number>'.

96 const dcBot = new DiscordClient({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.MESSAGE_CONTENT] });
                                                                                                                 ~~~~~~~~~~~~~~~


Found 1 error.

npm ERR! code 2
npm ERR! path C:\Users\Administrator\Desktop\TediCross-0.11.3
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2022-11-30T07_26_50_328Z-debug-0.log

C:\Users\Administrator\Desktop\TediCross-0.11.3>



any help please?

**Comment by trgwii** [comment]
I can't reproduce this.

Try removing your folder and cloning and running `npm install` into a new, empty folder.

**Comment by supercurio** [comment]
Same here, `npm install --production` fails with the same error.
The problem is not present on 0.11.2 or current master

**Comment by shemetz** [comment]
I had the same error show up when installing 0.11.3 today from the Releases zip.  I think the zip file needs to be updated.
